datanodeviewer changes (#872)
* datanodeviewer changes
- padding for chart trace
- missing key
- config debug message

* use checkout v4

* remove minimization for taipy-gui lib
to workaround the minimization error

  236.taipy-gui.js from Terser plugin
  Cannot read properties of undefined (reading 'TYPE')
  TypeError: Cannot read properties of undefined (reading 'TYPE')
      at shallow_cmp (C:\Users\jeu\Projects\taipy\frontend\taipy-gui\node_modules\terser\dist\bundle.min.js:11252:33)
      at equivalent_to (C:\Users\jeu\Projects\taipy\frontend\taipy-gui\node_modules\terser\dist\bundle.min.js:11257:10)
      at AST_Number.equivalent_to (C:\Users\jeu\Projects\taipy\frontend\taipy-gui\node_modules\terser\dist\bundle.min.js:18771:12)
      at C:\Users\jeu\Projects\taipy\frontend\taipy-gui\node_modules\terser\dist\bundle.min.js:20980:45

* use a valid terser !

---------

Co-authored-by: Fred Lefévère-Laoide <Fred.Lefevere-Laoide@Taipy.io>